# Generated by Django 2.2.4 on 2019-11-08 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('pk_tree', models.AutoField(primary_key=True, serialize=False)),
                ('tree_type', models.CharField(choices=[('Avocado', 'Avocado'), ('Pineapple', 'Pineapple'), ('Banana', 'Banana'), ('Persimmon', 'Persimmon'), ('Coconut', 'Coconut'), ('FIG', 'FIG'), ('Guava', 'Guava'), ('Jabuticaba', 'Jabuticaba'), ('Orange', 'Orange'), ('Lemon', 'Lemon'), ('Apple', 'Apple'), ('Papaya', 'Papaya'), ('Mango', 'Mango'), ('Passion Fruit', 'Passion Fruit'), ('Quince', 'Quince'), ('Nectarine', 'Nectarine'), ('Loquat', 'Loquat'), ('Pear', 'Pear'), ('Pequizeiro', 'Pequizeiro'), ('Tangerine', 'Tangerine'), ('Peach', 'Peach'), ('Vine', 'Vine')], max_length=13, verbose_name='Tree of type')),
                ('number_of_tree', models.IntegerField(default=1, verbose_name='Number of tree')),
                ('tree_height', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Average tree height')),
                ('pk_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trees', to='property.Property', verbose_name='Property trees')),
            ],
            options={
                'unique_together': {('pk_property', 'tree_type')},
            },
        ),
        migrations.CreateModel(
            name='HarvestMonth',
            fields=[
                ('pk_harvest_month', models.AutoField(primary_key=True, serialize=False)),
                ('harvest_month', models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=9, verbose_name='Harvest month')),
                ('pk_tree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harvest_months', to='tree.Tree')),
            ],
            options={
                'verbose_name_plural': 'Harvest Months',
                'unique_together': {('pk_tree', 'harvest_month')},
            },
        ),
    ]
