# Generated by Django 2.2.4 on 2019-11-14 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tree',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='static/trees'),
        ),
    ]
