# Generated by Django 2.2.4 on 2019-11-14 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('property', '0001_initial'),
        ('harvest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='harvest',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harvests', to='property.Property', verbose_name='Property harvests'),
        ),
    ]
