# Generated by Django 2.2.4 on 2019-11-08 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL, verbose_name='Property owner'),
        ),
        migrations.AlterUniqueTogether(
            name='property',
            unique_together={('BRZipCode', 'type_of_address', 'address')},
        ),
    ]
